### PR TITLE
Fix typos in Built Ins for Numbers

### PR DESCRIPTION
**Pull request by yuchi**
Please verify those are not written wrong on pourpose.

### CODE REVIEW

**Comment by yuchi** [comment]
Also, is editing the HTMLs the correct approach to propose a change? I cannot find any documentation on this… I expected to find some ASCIIDOC or MD file somewhere.

**Comment by ddekany** [comment]
These HTML-s are generated from https://github.com/apache/freemarker/blob/2.3-gae/src/manual/en_US/book.xml (XDocbok format). But I will do the fixing in the xml based on what you have committed.

**Comment by ddekany** [comment]
And actually "multipier" is a typo in the decimal format parser... fixed that in the code as well (will recognize both spellings in 2.3.29).

**Comment by yuchi** [comment]
Thanks so much for taking care of it for me!
May I suggest to revise the documentation on how to contribute? A good approach is to split every page in a different file, and then link to them through a «edit this page» link.

About the `multipier` thing… that’s gonna be a pain to document…

Be free to close this PR once the changes land!

**Comment by ddekany** [comment]
Well, at least we could provide a link to the source file on Git (be it one big or several smaller XML-s).

Can you please close this PR? Because I can't. (ASF has changed how Github integration works, and now the old trick doesn't work apparently.)

**Pull request closed without merging**
